DROP TABLE IF EXISTS ble;
DROP TABLE IF EXISTS datatypes;

CREATE TABLE ble (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mac TEXT UNIQUE NOT NULL,
  advtype TEXT NOT NULL,
  rssi INTEGER NOT NULL,
  timestamp TIMESTAMP NOT NULL
);

CREATE TABLE datatypes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  raw TEXT NOT NULL,
  FOREIGN KEY (id) REFERENCES ble (id)
);