DROP TABLE IF EXISTS ble;
DROP TABLE IF EXISTS datatypes;
DROP TABLE IF EXISTS user;

CREATE TABLE ble (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  address TEXT UNIQUE NOT NULL,
  advtype TEXT NOT NULL,
  rssi INTEGER NOT NULL,
  timestamp TIMESTAMP NOT NULL
);

CREATE TABLE datatypes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  raw TEXT NOT NULL,
  FOREIGN KEY (id) REFERENCES ble (id)
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);