DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS datatypes;
DROP TABLE IF EXISTS user;

CREATE TABLE devices (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mac TEXT UNIQUE NOT NULL,
  type TEXT NOT NULL,
  rssi INTEGER NOT NULL
);

CREATE TABLE datatypes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  type INTEGER NOT NULL, 
  raw TEXT NOT NULL,
  FOREIGN KEY (id) REFERENCES devices (id)
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  jti TEXT UNIQUE
);

INSERT INTO devices as d (mac, type, rssi) VALUES ('C1:BB:C2:C9:71:5E', 'ConnectableUndirected', -56)